# Generated by Django 3.2.9 on 2021-11-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univercity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='StudentCode',
            new_name='Code',
        ),
    ]
